### ISSUE TITLE
compile on armv7 is broken with: ../hwy/ops/arm_neon-inl.h:4296:42: error: call of overloaded ‘UpperHalf(hwy::N_NEON::Full64<short int>&, hwy::N_NEON::Vec128<short int, 8>&)’ is ambiguous

### ISSUE THREAD

**Issue by stefson** [google/highway#1145]
I noticed the big update the other day and gave it a try with gcc-10.4.0 and -mfpu=neon-vfpv4, to these results: 

```
/var/tmp/portage/dev-cpp/highway-9999/work/highway-9999/hwy/ops/arm_neon-inl.h:4296:42: error: call of overloaded ‘UpperHalf(hwy::N_NEON::Full64<short int>&, hwy::N_NEON::Vec128<short int, 8>&)’ is ambiguous
/var/tmp/portage/dev-cpp/highway-9999/work/highway-9999/hwy/ops/arm_neon-inl.h:4296:64: error: call of overloaded ‘UpperHalf(hwy::N_NEON::Full64<short int>&, hwy::N_NEON::Vec128<short int, 8>&)’ is ambiguous
/var/tmp/portage/dev-cpp/highway-9999/work/highway-9999/hwy/ops/arm_neon-inl.h:4415:62: error: call of overloaded ‘UpperHalf(hwy::N_NEON::Half<const hwy::N_NEON::Simd<int, 4, 0> >&, hwy::N_NEON::Vec128<int, 4>&)’ is ambiguous
/var/tmp/portage/dev-cpp/highway-9999/work/highway-9999/hwy/ops/arm_neon-inl.h:4417:62: error: call of overloaded ‘UpperHalf(hwy::N_NEON::Half<const hwy::N_NEON::Simd<int, 4, 0> >&, hwy::N_NEON::Vec128<int, 4>&)’ is ambiguous
/var/tmp/portage/dev-cpp/highway-9999/work/highway-9999/hwy/ops/arm_neon-inl.h:4296:42: error: call of overloaded ‘UpperHalf(hwy::N_NEON::Full64<short int>&, hwy::N_NEON::Vec128<short int, 8>&)’ is ambiguous
/var/tmp/portage/dev-cpp/highway-9999/work/highway-9999/hwy/ops/arm_neon-inl.h:4296:64: error: call of overloaded ‘UpperHalf(hwy::N_NEON::Full64<short int>&, hwy::N_NEON::Vec128<short int, 8>&)’ is ambiguous
/var/tmp/portage/dev-cpp/highway-9999/work/highway-9999/hwy/ops/arm_neon-inl.h:4415:62: error: call of overloaded ‘UpperHalf(hwy::N_NEON::Half<const hwy::N_NEON::Simd<int, 4, 0> >&, hwy::N_NEON::Vec128<int, 4>&)’ is ambiguous
/var/tmp/portage/dev-cpp/highway-9999/work/highway-9999/hwy/ops/arm_neon-inl.h:4417:62: error: call of overloaded ‘UpperHalf(hwy::N_NEON::Half<const hwy::N_NEON::Simd<int, 4, 0> >&, hwy::N_NEON::Vec128<int, 4>&)’ is ambiguous
/var/tmp/portage/dev-cpp/highway-9999/work/highway-9999/hwy/ops/arm_neon-inl.h:4296:42: error: call of overloaded ‘UpperHalf(hwy::N_NEON::Full64<short int>&, hwy::N_NEON::Vec128<short int, 8>&)’ is ambiguous
/var/tmp/portage/dev-cpp/highway-9999/work/highway-9999/hwy/ops/arm_neon-inl.h:4296:64: error: call of overloaded ‘UpperHalf(hwy::N_NEON::Full64<short int>&, hwy::N_NEON::Vec128<short int, 8>&)’ is ambiguous
/var/tmp/portage/dev-cpp/highway-9999/work/highway-9999/hwy/ops/arm_neon-inl.h:4415:62: error: call of overloaded ‘UpperHalf(hwy::N_NEON::Half<const hwy::N_NEON::Simd<int, 4, 0> >&, hwy::N_NEON::Vec128<int, 4>&)’ is ambiguous
/var/tmp/portage/dev-cpp/highway-9999/work/highway-9999/hwy/ops/arm_neon-inl.h:4417:62: error: call of overloaded ‘UpperHalf(hwy::N_NEON::Half<const hwy::N_NEON::Simd<int, 4, 0> >&, hwy::N_NEON::Vec128<int, 4>&)’ is ambiguous
/var/tmp/portage/dev-cpp/highway-9999/work/highway-9999/hwy/ops/arm_neon-inl.h:4296:42: error: call of overloaded ‘UpperHalf(hwy::N_NEON::Full64<short int>&, hwy::N_NEON::Vec128<short int, 8>&)’ is ambiguous
/var/tmp/portage/dev-cpp/highway-9999/work/highway-9999/hwy/ops/arm_neon-inl.h:4296:64: error: call of overloaded ‘UpperHalf(hwy::N_NEON::Full64<short int>&, hwy::N_NEON::Vec128<short int, 8>&)’ is ambiguous
/var/tmp/portage/dev-cpp/highway-9999/work/highway-9999/hwy/ops/arm_neon-inl.h:4415:62: error: call of overloaded ‘UpperHalf(hwy::N_NEON::Half<const hwy::N_NEON::Simd<int, 4, 0> >&, hwy::N_NEON::Vec128<int, 4>&)’ is ambiguous
/var/tmp/portage/dev-cpp/highway-9999/work/highway-9999/hwy/ops/arm_neon-inl.h:4417:62: error: call of overloaded ‘UpperHalf(hwy::N_NEON::Half<const hwy::N_NEON::Simd<int, 4, 0> >&, hwy::N_NEON::Vec128<int, 4>&)’ is ambiguous
/var/tmp/portage/dev-cpp/highway-9999/work/highway-9999/hwy/ops/arm_neon-inl.h:4296:42: error: call of overloaded ‘UpperHalf(hwy::N_NEON::Full64<short int>&, hwy::N_NEON::Vec128<short int, 8>&)’ is ambiguous
/var/tmp/portage/dev-cpp/highway-9999/work/highway-9999/hwy/ops/arm_neon-inl.h:4296:64: error: call of overloaded ‘UpperHalf(hwy::N_NEON::Full64<short int>&, hwy::N_NEON::Vec128<short int, 8>&)’ is ambiguous
/var/tmp/portage/dev-cpp/highway-9999/work/highway-9999/hwy/ops/arm_neon-inl.h:4415:62: error: call of overloaded ‘UpperHalf(hwy::N_NEON::Half<const hwy::N_NEON::Simd<int, 4, 0> >&, hwy::N_NEON::Vec128<int, 4>&)’ is ambiguous
/var/tmp/portage/dev-cpp/highway-9999/work/highway-9999/hwy/ops/arm_neon-inl.h:4417:62: error: call of overloaded ‘UpperHalf(hwy::N_NEON::Half<const hwy::N_NEON::Simd<int, 4, 0> >&, hwy::N_NEON::Vec128<int, 4>&)’ is ambiguous
/var/tmp/portage/dev-cpp/highway-9999/work/highway-9999/hwy/ops/arm_neon-inl.h:4296:42: error: call of overloaded ‘UpperHalf(hwy::N_NEON::Full64<short int>&, hwy::N_NEON::Vec128<short int, 8>&)’ is ambiguous
/var/tmp/portage/dev-cpp/highway-9999/work/highway-9999/hwy/ops/arm_neon-inl.h:4296:64: error: call of overloaded ‘UpperHalf(hwy::N_NEON::Full64<short int>&, hwy::N_NEON::Vec128<short int, 8>&)’ is ambiguous
/var/tmp/portage/dev-cpp/highway-9999/work/highway-9999/hwy/ops/arm_neon-inl.h:4415:62: error: call of overloaded ‘UpperHalf(hwy::N_NEON::Half<const hwy::N_NEON::Simd<int, 4, 0> >&, hwy::N_NEON::Vec128<int, 4>&)’ is ambiguous
/var/tmp/portage/dev-cpp/highway-9999/work/highway-9999/hwy/ops/arm_neon-inl.h:4417:62: error: call of overloaded ‘UpperHalf(hwy::N_NEON::Half<const hwy::N_NEON::Simd<int, 4, 0> >&, hwy::N_NEON::Vec128<int, 4>&)’ is ambiguous
/var/tmp/portage/dev-cpp/highway-9999/work/highway-9999/hwy/ops/arm_neon-inl.h:4296:42: error: call of overloaded ‘UpperHalf(hwy::N_NEON::Full64<short int>&, hwy::N_NEON::Vec128<short int, 8>&)’ is ambiguous
/var/tmp/portage/dev-cpp/highway-9999/work/highway-9999/hwy/ops/arm_neon-inl.h:4296:64: error: call of overloaded ‘UpperHalf(hwy::N_NEON::Full64<short int>&, hwy::N_NEON::Vec128<short int, 8>&)’ is ambiguous
/var/tmp/portage/dev-cpp/highway-9999/work/highway-9999/hwy/ops/arm_neon-inl.h:4415:62: error: call of overloaded ‘UpperHalf(hwy::N_NEON::Half<const hwy::N_NEON::Simd<int, 4, 0> >&, hwy::N_NEON::Vec128<int, 4>&)’ is ambiguous
/var/tmp/portage/dev-cpp/highway-9999/work/highway-9999/hwy/ops/arm_neon-inl.h:4417:62: error: call of overloaded ‘UpperHalf(hwy::N_NEON::Half<const hwy::N_NEON::Simd<int, 4, 0> >&, hwy::N_NEON::Vec128<int, 4>&)’ is ambiguous
/var/tmp/portage/dev-cpp/highway-9999/work/highway-9999/hwy/ops/arm_neon-inl.h:4296:42: error: call of overloaded ‘UpperHalf(hwy::N_NEON::Full64<short int>&, hwy::N_NEON::Vec128<short int, 8>&)’ is ambiguous
/var/tmp/portage/dev-cpp/highway-9999/work/highway-9999/hwy/ops/arm_neon-inl.h:4296:64: error: call of overloaded ‘UpperHalf(hwy::N_NEON::Full64<short int>&, hwy::N_NEON::Vec128<short int, 8>&)’ is ambiguous
/var/tmp/portage/dev-cpp/highway-9999/work/highway-9999/hwy/ops/arm_neon-inl.h:4415:62: error: call of overloaded ‘UpperHalf(hwy::N_NEON::Half<const hwy::N_NEON::Simd<int, 4, 0> >&, hwy::N_NEON::Vec128<int, 4>&)’ is ambiguous
/var/tmp/portage/dev-cpp/highway-9999/work/highway-9999/hwy/ops/arm_neon-inl.h:4417:62: error: call of overloaded ‘UpperHalf(hwy::N_NEON::Half<const hwy::N_NEON::Simd<int, 4, 0> >&, hwy::N_NEON::Vec128<int, 4>&)’ is ambiguous
/var/tmp/portage/dev-cpp/highway-9999/work/highway-9999/hwy/ops/arm_neon-inl.h:4296:42: error: call of overloaded ‘UpperHalf(hwy::N_NEON::Full64<short int>&, hwy::N_NEON::Vec128<short int, 8>&)’ is ambiguous
/var/tmp/portage/dev-cpp/highway-9999/work/highway-9999/hwy/ops/arm_neon-inl.h:4296:64: error: call of overloaded ‘UpperHalf(hwy::N_NEON::Full64<short int>&, hwy::N_NEON::Vec128<short int, 8>&)’ is ambiguous
/var/tmp/portage/dev-cpp/highway-9999/work/highway-9999/hwy/ops/arm_neon-inl.h:4415:62: error: call of overloaded ‘UpperHalf(hwy::N_NEON::Half<const hwy::N_NEON::Simd<int, 4, 0> >&, hwy::N_NEON::Vec128<int, 4>&)’ is ambiguous
/var/tmp/portage/dev-cpp/highway-9999/work/highway-9999/hwy/ops/arm_neon-inl.h:4417:62: error: call of overloaded ‘UpperHalf(hwy::N_NEON::Half<const hwy::N_NEON::Simd<int, 4, 0> >&, hwy::N_NEON::Vec128<int, 4>&)’ is ambiguous
/var/tmp/portage/dev-cpp/highway-9999/work/highway-9999/hwy/ops/arm_neon-inl.h:4296:42: error: call of overloaded ‘UpperHalf(hwy::N_NEON::Full64<short int>&, hwy::N_NEON::Vec128<short int, 8>&)’ is ambiguous
/var/tmp/portage/dev-cpp/highway-9999/work/highway-9999/hwy/ops/arm_neon-inl.h:4296:64: error: call of overloaded ‘UpperHalf(hwy::N_NEON::Full64<short int>&, hwy::N_NEON::Vec128<short int, 8>&)’ is ambiguous
/var/tmp/portage/dev-cpp/highway-9999/work/highway-9999/hwy/ops/arm_neon-inl.h:4415:62: error: call of overloaded ‘UpperHalf(hwy::N_NEON::Half<const hwy::N_NEON::Simd<int, 4, 0> >&, hwy::N_NEON::Vec128<int, 4>&)’ is ambiguous
/var/tmp/portage/dev-cpp/highway-9999/work/highway-9999/hwy/ops/arm_neon-inl.h:4417:62: error: call of overloaded ‘UpperHalf(hwy::N_NEON::Half<const hwy::N_NEON::Simd<int, 4, 0> >&, hwy::N_NEON::Vec128<int, 4>&)’ is ambiguous
/var/tmp/portage/dev-cpp/highway-9999/work/highway-9999/hwy/ops/arm_neon-inl.h:4296:42: error: call of overloaded ‘UpperHalf(hwy::N_NEON::Full64<short int>&, hwy::N_NEON::Vec128<short int, 8>&)’ is ambiguous
/var/tmp/portage/dev-cpp/highway-9999/work/highway-9999/hwy/ops/arm_neon-inl.h:4296:64: error: call of overloaded ‘UpperHalf(hwy::N_NEON::Full64<short int>&, hwy::N_NEON::Vec128<short int, 8>&)’ is ambiguous
/var/tmp/portage/dev-cpp/highway-9999/work/highway-9999/hwy/ops/arm_neon-inl.h:4415:62: error: call of overloaded ‘UpperHalf(hwy::N_NEON::Half<const hwy::N_NEON::Simd<int, 4, 0> >&, hwy::N_NEON::Vec128<int, 4>&)’ is ambiguous
/var/tmp/portage/dev-cpp/highway-9999/work/highway-9999/hwy/ops/arm_neon-inl.h:4417:62: error: call of overloaded ‘UpperHalf(hwy::N_NEON::Half<const hwy::N_NEON::Simd<int, 4, 0> >&, hwy::N_NEON::Vec128<int, 4>&)’ is ambiguous
```

regressed by https://github.com/google/highway/commit/20bda6cb6884ea38103974311a3a6714239f9e8e

full build.log: [build.log.gz](https://github.com/google/highway/files/10802004/build.log.gz)

**Comment by jan-wassenberg** [comment]
Thanks for letting us know. We tested with GCC 10 and neon but not the combination of those two. Can repro the issue, working on it :)

**Comment by stefson** [comment]
Yes, that makes it compile, thank you. 

It is armv7 which is affected though, propably doesn't matter?

**Comment by jan-wassenberg** [comment]
Thanks for verifying the fix. I tested both arm7 and arm8, but let's rename the CL to NEON to cover both :)
