### PR TITLE
Fix for x86 _Float16 compilation errors with Clang 15

### PR DESCRIPTION
**Pull request by johnplatts**
This pull request fixes compilation errors on x86_64 with pre-release versions of Clang 15.

Support for _Float16 on SSE2/SSSE3/SSE4/AVX2 was added to Clang in LLVM revision [abeeae570efff38dceccf68f5352809c58ffdda2](https://github.com/llvm/llvm-project/commit/abeeae570efff38dceccf68f5352809c58ffdda2), which was integrated into the final Clang 15.0.0 release.

Both GCC and Clang define the `__FLT16_MAX__` macro if the `_Float16` type is available. The addition of the `defined(__FLT16_MAX__)` check in this pull request should prevent compilation errors with pre-release versions of Clang 15.

### CODE REVIEW

**Comment by kleisauke** [comment]
I confirm that this fixes the build failure mentioned in https://github.com/google/highway/pull/1950#discussion_r1477424103. Tested by doing:
```console
$ git clone https://github.com/google/oss-fuzz.git
$ cd oss-fuzz/
$ sed -i 's|https://github.com/google/highway.git|--branch hwy_x86_f16_fix_020724 https://github.com/johnplatts/jep_google_highway.git highway|' projects/libvips/Dockerfile
$ python infra/helper.py build_image libvips
$ python infra/helper.py build_fuzzers --sanitizer address libvips
```

It looks like OSS-Fuzz is indeed using a pre-release version of Clang 15, namely [`llvmorg-15-init-1464-gbf7f8d6f`](https://github.com/google/oss-fuzz/blob/08131018879ce27371e96c576e93d329a1ecd10c/infra/base-images/base-clang/checkout_build_install_llvm.sh#L53) which probably corresponds to https://github.com/llvm/llvm-project/commit/bf7f8d6fa6f460bf0a16ffec319cd71592216bf4.

**Review by jan-wassenberg — APPROVED** [review]
Nice, thank you @johnplatts for fixing this :)
