### ISSUE TITLE
1.4.0 fails to build on FreeBSD

### ISSUE THREAD

**Issue by jbeich** [google/highway#3007]
Regressed by #2994. Tested on FreeBSD 13.5, 15.0, -CURRENT.

```c++
$ cmake -DBUILD_TESTING=OFF -B /tmp/highway_build
$ cmake --build /tmp/highway_build
In file included from hwy/contrib/thread_pool/thread_pool.cc:16:
In file included from hwy/contrib/thread_pool/thread_pool.h:38:
hwy/contrib/thread_pool/futex.h:192:21: error: no matching function for call to '_umtx_op'
  192 |     const int ret = _umtx_op(address, UMTX_OP_WAIT_UINT_PRIVATE,
      |                     ^~~~~~~~
/usr/include/sys/umtx.h:137:5: note: candidate function not viable: 1st argument ('volatile void *') would lose volatile qualifier
  137 | int _umtx_op(void *obj, int op, u_long val, void *uaddr, void *uaddr2);
      |     ^        ~~~~~~~~~
1 error generated.
```

**Comment by jan-wassenberg** [comment]
Thanks for reporting.
Can you confirm that the following fixes the build?
```
  // _umtx_op with UMTX_OP_WAIT_UINT_PRIVATE: process-private futex on FreeBSD.
  void* address = const_cast<void*>(static_cast<const void*>(&current));
  for (;;) {
    const uint32_t next = current.load(acq);
    if (next != prev) return next;
    const int ret = _umtx_op(address, UMTX_OP_WAIT_UINT_PRIVATE,
                             static_cast<u_long>(prev), nullptr, nullptr);
    if (ret == -1) {
      HWY_DASSERT(errno == EAGAIN || errno == EINTR);
    }
  }
```

**Comment by jbeich** [comment]
I confirm, builds fine with your patch.

**Comment by jan-wassenberg** [comment]
Thanks, landing this shortly :)
