### ISSUE TITLE
failure when linking tests/image_test on ppc64/s390x

### ISSUE THREAD

**Issue by sharkcz** [google/highway#185]
I have tested the recent multi-arch fixes and it looks almost perfect :-) But there is a failure when linking `tests/image_test` when I try building from commit d81d8bce466a38078afd5773d6c4ebc6353836d1 on Fedora on a ppc64le or a s390x system.
````
[ 70%] Linking CXX executable tests/image_test
/usr/bin/cmake -E cmake_link_script CMakeFiles/image_test.dir/link.txt --verbose=1
/usr/bin/c++ -O2 -g -DNDEBUG -fPIE -pie CMakeFiles/image_test.dir/hwy/contrib/image/image_test.cc.o -o tests/image_test  libhwy.a lib/libgtest.a lib/libgtest_main.a lib/libgtest.a -lpthread 
/usr/bin/ld: CMakeFiles/image_test.dir/hwy/contrib/image/image_test.cc.o: in function `hwy::Image<unsigned char>::Image(unsigned long, unsigned long)':
/home/sharkcz/projects/highway/hwy/contrib/image/image.h:163: undefined reference to `hwy::ImageBase::ImageBase(unsigned long, unsigned long, unsigned long)'
/usr/bin/ld: CMakeFiles/image_test.dir/hwy/contrib/image/image_test.cc.o: in function `hwy::Image<unsigned char>::InitializePaddingForUnalignedAccesses()':
/home/sharkcz/projects/highway/hwy/contrib/image/image.h:169: undefined reference to `hwy::ImageBase::InitializePadding(unsigned long, hwy::ImageBase::Padding)'
/usr/bin/ld: CMakeFiles/image_test.dir/hwy/contrib/image/image_test.cc.o: in function `hwy::Image<unsigned short>::Image(unsigned long, unsigned long)':
/home/sharkcz/projects/highway/hwy/contrib/image/image.h:163: undefined reference to `hwy::ImageBase::ImageBase(unsigned long, unsigned long, unsigned long)'
/usr/bin/ld: CMakeFiles/image_test.dir/hwy/contrib/image/image_test.cc.o: in function `hwy::Image<unsigned short>::InitializePaddingForUnalignedAccesses()':
/home/sharkcz/projects/highway/hwy/contrib/image/image.h:169: undefined reference to `hwy::ImageBase::InitializePadding(unsigned long, hwy::ImageBase::Padding)'
/usr/bin/ld: CMakeFiles/image_test.dir/hwy/contrib/image/image_test.cc.o: in function `hwy::Image<unsigned int>::Image(unsigned long, unsigned long)':
/home/sharkcz/projects/highway/hwy/contrib/image/image.h:163: undefined reference to `hwy::ImageBase::ImageBase(unsigned long, unsigned long, unsigned long)'
/usr/bin/ld: CMakeFiles/image_test.dir/hwy/contrib/image/image_test.cc.o: in function `hwy::Image<unsigned int>::InitializePaddingForUnalignedAccesses()':
/home/sharkcz/projects/highway/hwy/contrib/image/image.h:169: undefined reference to `hwy::ImageBase::InitializePadding(unsigned long, hwy::ImageBase::Padding)'
/usr/bin/ld: CMakeFiles/image_test.dir/hwy/contrib/image/image_test.cc.o: in function `hwy::Image<unsigned long>::Image(unsigned long, unsigned long)':
/home/sharkcz/projects/highway/hwy/contrib/image/image.h:163: undefined reference to `hwy::ImageBase::ImageBase(unsigned long, unsigned long, unsigned long)'
/usr/bin/ld: CMakeFiles/image_test.dir/hwy/contrib/image/image_test.cc.o: in function `hwy::Image<unsigned long>::InitializePaddingForUnalignedAccesses()':
/home/sharkcz/projects/highway/hwy/contrib/image/image.h:169: undefined reference to `hwy::ImageBase::InitializePadding(unsigned long, hwy::ImageBase::Padding)'
/usr/bin/ld: CMakeFiles/image_test.dir/hwy/contrib/image/image_test.cc.o: in function `hwy::Image<unsigned long>::Image(unsigned long, unsigned long)':
/home/sharkcz/projects/highway/hwy/contrib/image/image.h:163: undefined reference to `hwy::ImageBase::ImageBase(unsigned long, unsigned long, unsigned long)'
/usr/bin/ld: CMakeFiles/image_test.dir/hwy/contrib/image/image_test.cc.o: in function `hwy::Image<unsigned int>::Image(unsigned long, unsigned long)':
/home/sharkcz/projects/highway/hwy/contrib/image/image.h:163: undefined reference to `hwy::ImageBase::ImageBase(unsigned long, unsigned long, unsigned long)'
/usr/bin/ld: CMakeFiles/image_test.dir/hwy/contrib/image/image_test.cc.o: in function `hwy::Image<unsigned short>::Image(unsigned long, unsigned long)':
/home/sharkcz/projects/highway/hwy/contrib/image/image.h:163: undefined reference to `hwy::ImageBase::ImageBase(unsigned long, unsigned long, unsigned long)'
/usr/bin/ld: CMakeFiles/image_test.dir/hwy/contrib/image/image_test.cc.o: in function `hwy::Image<unsigned char>::Image(unsigned long, unsigned long)':
/home/sharkcz/projects/highway/hwy/contrib/image/image.h:163: undefined reference to `hwy::ImageBase::ImageBase(unsigned long, unsigned long, unsigned long)'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/image_test.dir/build.make:107: tests/image_test] Error 1
````

**Comment by jan-wassenberg** [comment]
@sharkcz ah, this is caused by our recent split into hwy_contrib, thank you for pointing that out. Verified the fix on x86 and will send it for review shortly.
