### ISSUE TITLE
compile regression for aarch64 in libjxl caused by recent changes in d8867c9

### ISSUE THREAD

**Issue by stefson** [google/highway#836]
hey there, 

the recent changes in https://github.com/google/highway/commit/d8867c95df5c5bcd33562b3a24c96f5a54d298a8 have lead to further fallout for me when compiling libjxl libs against them, but only if compiling it for aarch64. compile for armv7a and amd64 is just fine. 

there are in total 2235 errors, something must have gone really wrong here? 

at least four different errors: 

```
../lib/jxl/fast_math-inl.h:133:10: error: ‘GetLane’ was not declared in this scope
```
```
../lib/jxl/fast_math-inl.h:115:24: error: ‘Abs’ was not declared in this scope
```
```
../lib/jxl/dct-inl.h:122:25: error: ‘MulAdd’ was not declared in this scope
```
```
../lib/jxl/dct-inl.h:78:17: error: invalid operands of types ‘__SVFloat32_t’ and ‘__SVFloat32_t’ to binary ‘operator+’
```

full build log is attched: [build.log.zip](https://github.com/google/highway/files/9063028/build.log.zip)

original bug, for reference: https://github.com/libjxl/libjxl/issues/1582

**Comment by eustas** [comment]
Does that affect clang builds?

**Comment by jan-wassenberg** [comment]
libjxl has committed a fix; unfortunately there is a typo, I am following up with them.

**Comment by stefson** [comment]
thanks for the update. do you care to link back the typo or the issue at libjxl?

**Comment by jan-wassenberg** [comment]
Sure, the change was https://github.com/libjxl/libjxl/commit/3199321bf0fab8a82e9fcb7323bbf50720fdaddb - it uses `HWY_DISABLE_TARGETS` but the correct spelling is `HWY_DISABLED_TARGETS`.

**Comment by eustas** [comment]
Landing https://github.com/libjxl/libjxl/pull/1642 that fixed the typo

**Comment by stefson** [comment]
indeed, the typo fix solves the issue. thank you :)

**Comment by jan-wassenberg** [comment]
Thanks @eustas !
