### ISSUE TITLE
inlining failed in call to ‘always_inline’ ‘void vst1q_u64(uint64_t*, uint64x2_t)’: target specific option mismatch 11002 | vst1q_u64 (uint64_t * __a, uint64x2_t __b)

### ISSUE THREAD

**Issue by stefson** [google/highway#834]
hi, this is most likely a regression from https://github.com/google/highway/commit/d8867c95df5c5bcd33562b3a24c96f5a54d298a8

compiler is gcc-10.4.0 on armhf

```
[8/38] /usr/bin/armv7a-unknown-linux-gnueabihf-g++ -DHWY_SHARED_DEFINE -Dhwy_contrib_EXPORTS -I/var/tmp/portage/portage/dev-cpp/highway-9999/work/highway-9999  -O2 -pipe -fomit-frame-pointer -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -Wno-builtin-macro-redefined -D__DATE__=\"redacted\" -D__TIMESTAMP__=\"redacted\" -D__TIME__=\"redacted\" -fmerge-all-constants -Wall -Wextra -Wconversion -Wsign-conversion -Wvla -Wnon-virtual-dtor -fmath-errno -fno-exceptions -MD -MT CMakeFiles/hwy_contrib.dir/hwy/contrib/sort/vqsort_128a.cc.o -MF CMakeFiles/hwy_contrib.dir/hwy/contrib/sort/vqsort_128a.cc.o.d -o CMakeFiles/hwy_contrib.dir/hwy/contrib/sort/vqsort_128a.cc.o -c /var/tmp/portage/portage/dev-cpp/highway-9999/work/highway-9999/hwy/contrib/sort/vqsort_128a.cc
FAILED: CMakeFiles/hwy_contrib.dir/hwy/contrib/sort/vqsort_128a.cc.o 
/usr/bin/armv7a-unknown-linux-gnueabihf-g++ -DHWY_SHARED_DEFINE -Dhwy_contrib_EXPORTS -I/var/tmp/portage/portage/dev-cpp/highway-9999/work/highway-9999  -O2 -pipe -fomit-frame-pointer -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -Wno-builtin-macro-redefined -D__DATE__=\"redacted\" -D__TIMESTAMP__=\"redacted\" -D__TIME__=\"redacted\" -fmerge-all-constants -Wall -Wextra -Wconversion -Wsign-conversion -Wvla -Wnon-virtual-dtor -fmath-errno -fno-exceptions -MD -MT CMakeFiles/hwy_contrib.dir/hwy/contrib/sort/vqsort_128a.cc.o -MF CMakeFiles/hwy_contrib.dir/hwy/contrib/sort/vqsort_128a.cc.o.d -o CMakeFiles/hwy_contrib.dir/hwy/contrib/sort/vqsort_128a.cc.o -c /var/tmp/portage/portage/dev-cpp/highway-9999/work/highway-9999/hwy/contrib/sort/vqsort_128a.cc
In file included from /var/tmp/portage/portage/dev-cpp/highway-9999/work/highway-9999/hwy/foreach_target.h:23,
                 from /var/tmp/portage/portage/dev-cpp/highway-9999/work/highway-9999/hwy/contrib/sort/vqsort_128a.cc:20:
/var/tmp/portage/portage/dev-cpp/highway-9999/work/highway-9999/hwy/targets.h: In function ‘std::vector<unsigned int> hwy::SupportedAndGeneratedTargets()’:
/var/tmp/portage/portage/dev-cpp/highway-9999/work/highway-9999/hwy/detect_targets.h:438:50: warning: integer overflow in expression of type ‘int’ results in ‘-2147483648’ [-Woverflow]
  438 | #define HWY_TARGETS (HWY_ATTAINABLE_TARGETS & (2 * HWY_STATIC_TARGET - 1))
      |                                                  ^
/var/tmp/portage/portage/dev-cpp/highway-9999/work/highway-9999/hwy/targets.h:69:48: note: in expansion of macro ‘HWY_TARGETS’
   69 |   for (uint32_t targets = SupportedTargets() & HWY_TARGETS; targets != 0;
      |                                                ^~~~~~~~~~~
In file included from /var/tmp/portage/portage/dev-cpp/highway-9999/work/highway-9999/hwy/highway.h:25,
                 from /var/tmp/portage/portage/dev-cpp/highway-9999/work/highway-9999/hwy/contrib/sort/shared-inl.h:103,
                 from /var/tmp/portage/portage/dev-cpp/highway-9999/work/highway-9999/hwy/contrib/sort/traits128-inl.h:27,
                 from /var/tmp/portage/portage/dev-cpp/highway-9999/work/highway-9999/hwy/contrib/sort/vqsort_128a.cc:23,
                 from /var/tmp/portage/portage/dev-cpp/highway-9999/work/highway-9999/hwy/foreach_target.h:81,
                 from /var/tmp/portage/portage/dev-cpp/highway-9999/work/highway-9999/hwy/contrib/sort/vqsort_128a.cc:20:
/var/tmp/portage/portage/dev-cpp/highway-9999/work/highway-9999/hwy/targets.h: In member function ‘size_t hwy::ChosenTarget::GetIndex() const’:
/var/tmp/portage/portage/dev-cpp/highway-9999/work/highway-9999/hwy/detect_targets.h:438:50: warning: integer overflow in expression of type ‘int’ results in ‘-2147483648’ [-Woverflow]
  438 | #define HWY_TARGETS (HWY_ATTAINABLE_TARGETS & (2 * HWY_STATIC_TARGET - 1))
      |                                                  ^
/var/tmp/portage/portage/dev-cpp/highway-9999/work/highway-9999/hwy/targets.h:157:7: note: in definition of macro ‘HWY_CHOSEN_TARGET_SHIFT’
  157 |   ((((X) >> (HWY_HIGHEST_TARGET_BIT + 1 - HWY_MAX_DYNAMIC_TARGETS)) & \
      |       ^
/var/tmp/portage/portage/dev-cpp/highway-9999/work/highway-9999/hwy/targets.h:163:28: note: in expansion of macro ‘HWY_TARGETS’
  163 |   (HWY_CHOSEN_TARGET_SHIFT(HWY_TARGETS) | HWY_CHOSEN_TARGET_MASK_SCALAR | 1u)
      |                            ^~~~~~~~~~~
/var/tmp/portage/portage/dev-cpp/highway-9999/work/highway-9999/hwy/targets.h:267:47: note: in expansion of macro ‘HWY_CHOSEN_TARGET_MASK_TARGETS’
  267 |                                               HWY_CHOSEN_TARGET_MASK_TARGETS);
      |                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /var/tmp/portage/portage/dev-cpp/highway-9999/work/highway-9999/hwy/ops/arm_neon-inl.h:29,
                 from /var/tmp/portage/portage/dev-cpp/highway-9999/work/highway-9999/hwy/highway.h:322,
                 from /var/tmp/portage/portage/dev-cpp/highway-9999/work/highway-9999/hwy/contrib/sort/shared-inl.h:103,
                 from /var/tmp/portage/portage/dev-cpp/highway-9999/work/highway-9999/hwy/contrib/sort/traits128-inl.h:27,
                 from /var/tmp/portage/portage/dev-cpp/highway-9999/work/highway-9999/hwy/contrib/sort/vqsort_128a.cc:23,
                 from /var/tmp/portage/portage/dev-cpp/highway-9999/work/highway-9999/hwy/foreach_target.h:81,
                 from /var/tmp/portage/portage/dev-cpp/highway-9999/work/highway-9999/hwy/contrib/sort/vqsort_128a.cc:20:
/usr/lib/gcc/armv7a-unknown-linux-gnueabihf/10.4.0/include/arm_neon.h: In function ‘void hwy::N_NEON::StoreU(hwy::N_NEON::Vec128<long long unsigned int, 2>, hwy::N_NEON::Full128<long long unsigned int>, uint64_t*)’:
/usr/lib/gcc/armv7a-unknown-linux-gnueabihf/10.4.0/include/arm_neon.h:11002:1: error: inlining failed in call to ‘always_inline’ ‘void vst1q_u64(uint64_t*, uint64x2_t)’: target specific option mismatch
11002 | vst1q_u64 (uint64_t * __a, uint64x2_t __b)
      | ^~~~~~~~~
In file included from /var/tmp/portage/portage/dev-cpp/highway-9999/work/highway-9999/hwy/highway.h:322,
                 from /var/tmp/portage/portage/dev-cpp/highway-9999/work/highway-9999/hwy/contrib/sort/shared-inl.h:103,
                 from /var/tmp/portage/portage/dev-cpp/highway-9999/work/highway-9999/hwy/contrib/sort/traits128-inl.h:27,
                 from /var/tmp/portage/portage/dev-cpp/highway-9999/work/highway-9999/hwy/contrib/sort/vqsort_128a.cc:23,
                 from /var/tmp/portage/portage/dev-cpp/highway-9999/work/highway-9999/hwy/foreach_target.h:81,
                 from /var/tmp/portage/portage/dev-cpp/highway-9999/work/highway-9999/hwy/contrib/sort/vqsort_128a.cc:20:
/var/tmp/portage/portage/dev-cpp/highway-9999/work/highway-9999/hwy/ops/arm_neon-inl.h:2744:12: note: called from here
 2744 |   vst1q_u64(unaligned, v.raw);
      |   ~~~~~~~~~^~~~~~~~~~~~~~~~~~
```

full build log: [build.log.zip](https://github.com/google/highway/files/9062461/build.log.zip)

**Comment by jan-wassenberg** [comment]
@stefson 
hm, I'm mystified 😦 Here is the function definition I see from armhf gcc 10:
```
__extension__ extern __inline void
__attribute__  ((__always_inline__, __gnu_inline__, __artificial__))
vst1q_u64 (uint64_t * __a, uint64x2_t __b)
{
  __builtin_neon_vst1v2di ((__builtin_neon_di *) __a, (int64x2_t) __b);
}
```
Unlike the p64 version, which sets extra attributes, I don't see any here. If you comment out the call to vst1q_u64, are there any other errors?

For the warning, I think we can fix that by replacing 2 with 2ULL; we'll anyway soon make targets 64-bit.

**Comment by jan-wassenberg** [comment]
@stefson do you have any idea what might be happening? If not, it's an option to disable runtime dispatch for arm7 on this version of GCC.

**Comment by stefson** [comment]
could you guide me a little bit in how to disable runtime dispatch?

**Comment by jan-wassenberg** [comment]
Sure, in detect_targets.h we have a line `#if HWY_ARCH_X86 || (HWY_ARCH_ARM && HWY_COMPILER_GCC_ACTUAL && HWY_OS_LINUX)`. You can for example change `HWY_ARCH_ARM` to `HWY_ARCH_ARM_A64`.

**Comment by stefson** [comment]
do you mean as in: 

```
diff --git a/hwy/detect_targets.h b/hwy/detect_targets.h
index afc9154..7be7770 100644
--- a/hwy/detect_targets.h
+++ b/hwy/detect_targets.h
@@ -372,7 +372,7 @@
 
 // x86 compilers generally allow runtime dispatch. On Arm, currently only GCC
 // does, and we require Linux to detect CPU capabilities.
-#if HWY_ARCH_X86 || (HWY_ARCH_ARM && HWY_COMPILER_GCC_ACTUAL && HWY_OS_LINUX)
+#if HWY_ARCH_X86 || (HWY_ARCH_ARM_A64 && HWY_COMPILER_GCC_ACTUAL && HWY_OS_LINUX)
 #define HWY_HAVE_RUNTIME_DISPATCH 1
 #else
 #define HWY_HAVE_RUNTIME_DISPATCH 0
``` 

?

**Comment by jan-wassenberg** [comment]
Yes, looks good :) If this helps you, feel free to send this as a pull request, or we can do it if you prefer.

**Comment by stefson** [comment]
it helps indeed, but I need more time to iron this out - arm hardware really is slow.

**Comment by stefson** [comment]
I wonder about a sensible strategy for a fix on the compiler side?

**Comment by malaterre** [comment]
I cannot reproduce any compilation issue on armhf/gcc10|11|12.

For reference:

```
% grep -3 vst1q_u64 /usr/lib/gcc/arm-linux-gnueabihf/*/include/arm_neon.h
/usr/lib/gcc/arm-linux-gnueabihf/10/include/arm_neon.h-
/usr/lib/gcc/arm-linux-gnueabihf/10/include/arm_neon.h-__extension__ extern __inline void
/usr/lib/gcc/arm-linux-gnueabihf/10/include/arm_neon.h-__attribute__  ((__always_inline__, __gnu_inline__, __artificial__))
/usr/lib/gcc/arm-linux-gnueabihf/10/include/arm_neon.h:vst1q_u64 (uint64_t * __a, uint64x2_t __b)
/usr/lib/gcc/arm-linux-gnueabihf/10/include/arm_neon.h-{
/usr/lib/gcc/arm-linux-gnueabihf/10/include/arm_neon.h-  __builtin_neon_vst1v2di ((__builtin_neon_di *) __a, (int64x2_t) __b);
/usr/lib/gcc/arm-linux-gnueabihf/10/include/arm_neon.h-}
--
/usr/lib/gcc/arm-linux-gnueabihf/11/include/arm_neon.h-
/usr/lib/gcc/arm-linux-gnueabihf/11/include/arm_neon.h-__extension__ extern __inline void
/usr/lib/gcc/arm-linux-gnueabihf/11/include/arm_neon.h-__attribute__  ((__always_inline__, __gnu_inline__, __artificial__))
/usr/lib/gcc/arm-linux-gnueabihf/11/include/arm_neon.h:vst1q_u64 (uint64_t * __a, uint64x2_t __b)
/usr/lib/gcc/arm-linux-gnueabihf/11/include/arm_neon.h-{
/usr/lib/gcc/arm-linux-gnueabihf/11/include/arm_neon.h-  __builtin_neon_vst1v2di ((__builtin_neon_di *) __a, (int64x2_t) __b);
/usr/lib/gcc/arm-linux-gnueabihf/11/include/arm_neon.h-}
--
/usr/lib/gcc/arm-linux-gnueabihf/12/include/arm_neon.h-
/usr/lib/gcc/arm-linux-gnueabihf/12/include/arm_neon.h-__extension__ extern __inline void
/usr/lib/gcc/arm-linux-gnueabihf/12/include/arm_neon.h-__attribute__  ((__always_inline__, __gnu_inline__, __artificial__))
/usr/lib/gcc/arm-linux-gnueabihf/12/include/arm_neon.h:vst1q_u64 (uint64_t * __a, uint64x2_t __b)
/usr/lib/gcc/arm-linux-gnueabihf/12/include/arm_neon.h-{
/usr/lib/gcc/arm-linux-gnueabihf/12/include/arm_neon.h-  __builtin_neon_vst1v2di ((__builtin_neon_di *) __a, (int64x2_t) __b);
/usr/lib/gcc/arm-linux-gnueabihf/12/include/arm_neon.h-}
```

**Comment by stefson** [comment]
I see the same results as you for my gcc-10 armv7a cross compiler, but still it gives me the error without the now pushed patch.

**Comment by malaterre** [comment]
> I see the same results as you for my gcc-10 armv7a cross compiler, but still it gives me the error without the now pushed patch.

Add '--verbose' to the compilation line that is failing and post back. Eg.:

```
/usr/bin/armv7a-unknown-linux-gnueabihf-g++ --verbose -DHWY_SHARED_DEFINE -Dhwy_contrib_EXPORTS [...]
```

**Comment by jan-wassenberg** [comment]
@malaterre, good catch, thanks for pointing to that. vfpv4 is supported since 2009, I'd be surprised if anyone still cares about vfpv3.
set_macros-inl.h does:
```
#if HWY_ARCH_ARM_V7
#define HWY_TARGET_STR "+neon-vfpv4"
```
It makes sense that the compiler complains because arm_neon.h is compiled with the default target and only for Highway implementation and user code do we set vfpv4.

Here's an idea @stefson : does it help to, in arm_neon-inl.h move the following block to the line after `HWY_BEFORE_NAMESPACE();`?

```
HWY_DIAGNOSTICS(push)
HWY_DIAGNOSTICS_OFF(disable : 4701, ignored "-Wuninitialized")
#include <arm_neon.h>
HWY_DIAGNOSTICS(pop)
```

**Comment by stefson** [comment]
Can you please post a patch against latest git for your idea? The risk of a missunderstanding is too high if you ask me that way :D

**Comment by jan-wassenberg** [comment]
Sure, sent :)

**Comment by stefson** [comment]
with gcc-10.4.0: [latest-git+patch.log.gz](https://github.com/google/highway/files/9490486/latest-git%2Bpatch.log.gz)

this does not look good :-S

**Comment by malaterre** [comment]
> this does not look good :-S

try:

* https://github.com/google/highway/pull/966#issuecomment-1237150317

**Comment by malaterre** [comment]
@stefson can you try 55010e4b126d222acd6906ebdb32f723f94ccafb ?

**Comment by stefson** [comment]
it seems the compile is fixed by this commit: https://github.com/google/highway/commit/864d97bc74de6681d3e5e382582ddaa2a0837426

patching https://github.com/google/highway/commit/55010e4b126d222acd6906ebdb32f723f94ccafb on top of current git fails: 

```
/usr/lib/gcc/armv7a-unknown-linux-gnueabihf/10.4.0/include/arm_neon.h:11002:1: error: inlining failed in call to ‘always_inline’ ‘void vst1q_u64(uint64_t*, uint64x2_t)’: target specific option mismatch
/usr/lib/gcc/armv7a-unknown-linux-gnueabihf/10.4.0/include/arm_neon.h:10974:1: error: inlining failed in call to ‘always_inline’ ‘void vst1q_f32(float32_t*, float32x4_t)’: target specific option mismatch
/usr/lib/gcc/armv7a-unknown-linux-gnueabihf/10.4.0/include/arm_neon.h:10944:1: error: inlining failed in call to ‘always_inline’ ‘void vst1q_s16(int16_t*, int16x8_t)’: target specific option mismatch
/usr/lib/gcc/armv7a-unknown-linux-gnueabihf/10.4.0/include/arm_neon.h:10974:1: error: inlining failed in call to ‘always_inline’ ‘void vst1q_f32(float32_t*, float32x4_t)’: target specific option mismatch
/usr/lib/gcc/armv7a-unknown-linux-gnueabihf/10.4.0/include/arm_neon.h:11002:1: error: inlining failed in call to ‘always_inline’ ‘void vst1q_u64(uint64_t*, uint64x2_t)’: target specific option mismatch
/usr/lib/gcc/armv7a-unknown-linux-gnueabihf/10.4.0/include/arm_neon.h:10944:1: error: inlining failed in call to ‘always_inline’ ‘void vst1q_s16(int16_t*, int16x8_t)’: target specific option mismatch
/usr/lib/gcc/armv7a-unknown-linux-gnueabihf/10.4.0/include/arm_neon.h:10951:1: error: inlining failed in call to ‘always_inline’ ‘void vst1q_s32(int32_t*, int32x4_t)’: target specific option mismatch
/usr/lib/gcc/armv7a-unknown-linux-gnueabihf/10.4.0/include/arm_neon.h:10951:1: error: inlining failed in call to ‘always_inline’ ‘void vst1q_s32(int32_t*, int32x4_t)’: target specific option mismatch
/usr/lib/gcc/armv7a-unknown-linux-gnueabihf/10.4.0/include/arm_neon.h:10958:1: error: inlining failed in call to ‘always_inline’ ‘void vst1q_s64(int64_t*, int64x2_t)’: target specific option mismatch
/usr/lib/gcc/armv7a-unknown-linux-gnueabihf/10.4.0/include/arm_neon.h:10958:1: error: inlining failed in call to ‘always_inline’ ‘void vst1q_s64(int64_t*, int64x2_t)’: target specific option mismatch
/usr/lib/gcc/armv7a-unknown-linux-gnueabihf/10.4.0/include/arm_neon.h:11002:1: error: inlining failed in call to ‘always_inline’ ‘void vst1q_u64(uint64_t*, uint64x2_t)’: target specific option mismatch
```


full build log: [build.log.gz](https://github.com/google/highway/files/9496496/build.log.gz)

**Comment by stefson** [comment]
for **aarch64**, current git does fail with many errors ( full log: [aarch64-current-git-build.log.gz](https://github.com/google/highway/files/9496545/aarch64-current-git-build.log.gz) ) , which is fixed with the proposed patch from https://github.com/google/highway/commit/55010e4b126d222acd6906ebdb32f723f94ccafb

**Comment by jan-wassenberg** [comment]
Thank you, then we'll commit that patch shortly :)

**Comment by stefson** [comment]
yeah, lets watch the fireworks

**Comment by stefson** [comment]
armv7-gcc still broken with commit https://github.com/google/highway/commit/99340469dd310055f8f269ebe1621c9aaaa79322 , here is the build log: [build.log.gz](https://github.com/google/highway/files/9500330/build.log.gz)

**Comment by jan-wassenberg** [comment]
Thanks for sharing the result. I was unable to reproduce it with GCC 10.3 (godbolt lacks 10.4) and `-O2 -march=armv7-a -mfpu=vfpv3-d16`, and your `-O2 -mfloat-abi=hard -mfpu=vfpv3-d16 -marm -mlibarch=armv7-a+fp -march=armv7-a+fp`.
https://gcc.godbolt.org/z/KrYz818xY

**Comment by stefson** [comment]
can you please name me the gcc version (gcc-10.3.0 and later) which godbolt offers you?

**Comment by jan-wassenberg** [comment]
You can see them in the dropdown menu in the link above, where it currently says "ARM GCC 10.3.1" :) The next higher one is 11.1.

**Comment by stefson** [comment]
ah, got it! :D 

I can offer you a log of failed compile with gcc-11.3.0, which seems identically to me: [gcc-11.3.0-armv7a.log.gz](https://github.com/google/highway/files/9504768/gcc-11.3.0-armv7a.log.gz)

**Comment by jan-wassenberg** [comment]
:)
The question is not whether we can get it to fail with other compilers. Instead the problem appears to be the configuration of the compiler, because it works (see godbolt link) with 11.3 and the flags specified there.
Have you compiled gcc from source, or is it from a binary release?

**Comment by stefson** [comment]
I've opened a gentoo bug for this, hopefully someone more experienced from toolchain will take a look at it: https://bugs.gentoo.org/869077

**Comment by jan-wassenberg** [comment]
Nice, glad you've got feedback from the Gentoo bug :) Is the `HWY_CMAKE_ARM7` solution enough for you?

(I still don't know why the default flags cause this conflict, but I imagine most use cases will be fine with setting compiler flags that require an Arm from 2009 or later.)

**Comment by stefson** [comment]
so, I did compile on armv7a with neon and with gcc-10.4.0, and it passes. Also all tests are passing, yay! test compiling on armv7a+musl is still on my queue though. 

it seems libjxl now has a more or less similar hickup: https://github.com/libjxl/libjxl/issues/1748

**Comment by jan-wassenberg** [comment]
I believe this is now fully fixed thanks to @jolivain, please feel free to re-open if anything else comes up.

**Comment by MBkkt** [comment]
```
06:52:21 /home/jenkins/workspace/iresearch-release_aarch64/external/highway/hwy/ops/arm_neon-inl.h: In static member function ‘static decltype(auto) irs::simd::simd_helper<Aligned>::load(Simd, Ptr) [with Simd = hwy::N_NEON::Simd<unsigned int, 4, 0>; Ptr = unsigned int*; bool Aligned = false]’:
06:52:21 /home/jenkins/workspace/iresearch-release_aarch64/external/highway/hwy/ops/arm_neon-inl.h:2599:26: error: inlining failed in call to ‘always_inline’ ‘hwy::N_NEON::Vec128<unsigned int, 4> hwy::N_NEON::LoadU(hwy::N_NEON::Full128<unsigned int>, const uint32_t*)’: target specific option mismatch
06:52:21  2599 | HWY_API Vec128<uint32_t> LoadU(Full128<uint32_t> /* tag */,
```


```cpp
  template<typename Simd, typename Ptr>
  static decltype(auto) load(const Simd simd_tag, Ptr p) {
    if constexpr (Aligned) {
      return Load(simd_tag, p);
    } else {
      return LoadU(simd_tag, p);
    }
  }
```

Could you help please?

**Comment by jan-wassenberg** [comment]
hm, I believe the fix for this issue came after the 1.0.3 release that you seem to be using. We will do another release in the next few days.

Just to confirm: you are building for aarch64, right? If it's actually Arm V7, then you will want to add `-DHWY_CMAKE_ARM7=ON` to the CMake command line.

**Comment by MBkkt** [comment]
@jan-wassenberg Thanks for answer!

Yes it's definitely armv8, we don't have armv7 machines

I commented on this issue, because I tried some time ago and faced with it, then I see it resolved, decided to try another time, and faced with new issue.

In general I really suspect this cmake file doing something wrong :(
https://github.com/iresearch-toolkit/iresearch/blob/master/cmake/OptimizeForArchitecture.cmake

**Comment by stefson** [comment]
I've tested all kind of combinations, armv7 and aarch64, without any breakage with current git. Whats your toolchain and cpu, please?

**Comment by jan-wassenberg** [comment]
Thanks @stefson . I think one problem is indeed that they are overriding the compiler flags with a separate CMake file outside of Highway.

Seems that these lines are insufficient and possibly counterproductive:
https://github.com/iresearch-toolkit/iresearch/blob/master/cmake/OptimizeForArchitecture.cmake#L587

Does it help to replace with -march=armv8.2-a?

But another issue is that they are testing with Highway 1.0.3 which came before some of our fixes here.

**Comment by MBkkt** [comment]
@stefson 
I build our public repo with
```
cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DUSE_TESTS=On -DUSE_IPO=Off -DCMAKE_C_COMPILER=gcc-10 -DCMAKE_CXX_COMPILER=g++-10 -G 'Unix Makefiles' ..
```
unfortunately it needs some external packages: icu, boost, lz4

Then I see this in this cmake script.
```
06:49:35 CMake Warning at cmake/OptimizeForArchitecture.cmake:585 (message):
06:49:35   Architecture auto-detection for CMAKE_SYSTEM_PROCESSOR 'aarch64' is not
06:49:35   supported by OptimizeForArchitecture.cmake on ARM
06:49:35 Call Stack (most recent call first):
06:49:35   cmake/OptimizeForArchitecture.cmake:622 (OptimizeForArchitectureArm)
06:49:35   CMakeLists.txt:204 (OptimizeForArchitecture)
```

So I assume https://github.com/iresearch-toolkit/iresearch/blob/master/cmake/OptimizeForArchitecture.cmake#L622
this called and do nothing.
Also I assume it's real aarch64, probably I need to specify some flags?

**Comment by MBkkt** [comment]
Anyway thanks, probably I should do something with this broken cmake script before update highway

**Comment by MBkkt** [comment]
> Seems that these lines are insufficient and possibly counterproductive:

Agreed, because for us machine which run code can be with different processor but same architecture (in general we only support x86/armv8).

> I think one problem is indeed that they are overriding the compiler flags with a separate CMake file outside of Highway.

I want to remove this script, and measure difference, should I specify something additional.
Or maybe some approach that you can recommend?

Maybe I can specify highway cmake first and it will specify all needed flags instead of me?)

**Comment by jan-wassenberg** [comment]
Ah, it's good news that we're hitting the "auto" case, then this CMake file is indeed not doing anything.

On GCC+aarch64, Highway trunk works out of the box and generates code for all targets without any required flags:
https://gcc.godbolt.org/z/e4M94doPc

The 1.0.3 release might benefit from you adding `-march=armv8.2-a`.
