### ISSUE TITLE
sys/random.h: No such file or directory

### ISSUE THREAD

**Issue by yzazik** [google/highway#589]
Hello, trying to build on Linux with glibc 2.18 (can't upgrade), getting:

```cpp
hwy/contrib/sort/vqsort.cc:48:10: fatal error: sys/random.h: No such file or directory
 #include <sys/random.h>
          ^~~~~~~~~~~~~~

```

With a little bit digging, turns out `getrandom()` was added in glibc 2.25.

Well, first question, could this be remediated somehow? There are some suggestions [here](https://stackoverflow.com/questions/30800331/getrandom-syscall-in-c-not-found).

Second, if not, I need to escalate this to IT for upgrade, then the question would be what's highway's minimum required glibc version?

Thank you.

**Comment by yzazik** [comment]
@jan-wassenberg 

Agree, `-DVQSORT_SECURE_SEED=0` works but... rather inconvenient (at least using cmake) and requires user (ie, build/release management) knowledge.

About `# if __GLIBC__ > 2 || __GLIBC_MINOR__ > 24`, not that there is version 1.26 for example, but I guess you would want to have it in the way no one would have any more questions, so I ended up using this:

```cpp
#if (defined(linux) || defined(__linux__)) && \
    !(defined(ANDROID) || defined(__ANDROID__) || HWY_ARCH_RVV) && \
    __GLIBC_PREREQ(2, 25) // ie <sys/random.h> is available

```

One note though, `__GLIBC_PREREQ` is first defined in glibc 2.2 which was released on Nov 9th 2000, should be safe enough I think, but if you want it bulletproof, I guess, you could use something like `(((__GLIBC__ << 16) + __GLIBC_MINOR__) >= 0x20025)` instead.

**Comment by jan-wassenberg** [comment]
@yzazik thanks for confirming! I've learned that it pays to be more bulletproof for such system-specific code, so the proposed fix is a bit more thorough (to support other libc).

**Comment by yzazik** [comment]
@jan-wassenberg
Oh, man, well, again, this is won't happen in my case, but that wouldn't work, unlike regular defines (without `()`, like constants), all macros in the same `#if` have to be expanded, so you need extra nested `#if-#endif`. Try to `#undef` it to simulate (this won't build):
```cpp
#elif defined(__GLIBC__)
#undef __GLIBC_PREREQ       // simulate not defined
#if defined(__GLIBC_PREREQ) && __GLIBC_PREREQ(2, 25)
#define VQSORT_GETRANDOM 1
#else
#define VQSORT_GETRANDOM 0
#endif
#else
```

**Comment by jan-wassenberg** [comment]
Oh indeed, did not know that, thanks for pointing it out. I've audited all occurrences of defined(), that was the problematic occurrence.
