### ISSUE TITLE
sort_test fails to build on toolchains without native float16 (since 636d64d8)

### ISSUE THREAD

**Issue by dcsid** [google/highway#3112]
Since 636d64d8 ("Fix VQSelect sentinel/NaN handling", #3098), `sort_test.cc` fails to build on toolchains without native float16 support, where `hwy::float16_t` is the emulated struct:

- `sort_test.cc:298`: `std::iota(keys.begin(), keys.end(), T{0})` — no `float16_t` constructor from `int` (brace-init fails), and `std::iota` also requires `operator++`.
- `sort_test.cc:326`: `x == -kInf` — no unary `operator-` for the emulated `float16_t`.

Sample errors:

```
sort_test.cc:298:12: error: no matching function for call to 'hwy::float16_t::float16_t(<brace-enclosed initializer list>)'
sort_test.cc:326:34: error: no match for 'operator-' (operand type is 'const hwy::float16_t')
```

This currently fails on master (e.g. the CI run for 16933bd2) and on PRs based on it, in: GCC 9–12, Clang 11–15 (incl. x86_32), armv7, ppc64le, GCC-14 on LoongArch64, and the Windows LLVM (C++20) Meson build — i.e. everywhere `HWY_HAVE_FLOAT16` is 0. Newer compilers with native `_Float16` are unaffected.

Possibly `ConvertScalarTo<T>` for the iota seed and `ScalarNeg`/comparing via bit pattern (or `ConvertScalarTo<T>(-inf)`) for line 326 would keep it portable.

**Comment by dcsid** [comment]
With the iota/`-kInf` fixes, LoongArch gets further and hits a latent issue: `GetLane` for 2-byte lanes (`loongarch_lsx-inl.h:272`) does `static_cast<T>(__lsx_vpickve2gr_h(...))`, which does not compile for emulated `float16_t` (no construction from int). #3113 sidesteps it by guarding the f16 instantiation with `HWY_HAVE_FLOAT16`, matching `CallAllSortTraits`; the LSX `GetLane` may want `BitCastScalar` for f16/bf16.

**Comment by jan-wassenberg** [comment]
Thanks, my patch was missing the HWY_HAVE_FLOAT16/64 checks. This is being added in #3109. Unfortunately(?) our internal CI has float16 everywhere.

Let's think about whether to try to expand HWY_HAVE_SCALAR_F16_OPERATORS or the emulation. I'd think the former is pretty widespread, but our detection is a bit conservative. For example, ppcle64 is excluded without reason. Probably we should still land your fix for gcc9-12 (merging after 3109).

**Comment by dcsid** [comment]
I did some digging on the ppc64le angle. It looks like neither clang nor gcc exposes scalar `_Float16` on PowerPC. clang hard-errors with `_Float16 is not supported on this target`, and gcc has only open feature requests ([target/121525](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=121525), [/113484](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=113484)) to add it for Power9+, so adding PPC to the allowlist would likely just hard-error.

The emulation route you mentioned would still work everywhere though, by adding construction-from-`int` + unary minus to the `uint16_t`-backed `float16_t`. Happy to take that on if useful.

**Comment by jan-wassenberg** [comment]
Thanks for checking. Huh, surprised that ppc64 lacks float16 entirely.

I do think extending the emulation would be useful, we could ConvertScalarTo from value to f16 bits inside a ctor, and similarly provide the unary minus. I don't mind landing #3113 but it seems this will come up again, so emulation would be good in the long run and we'd welcome a PR.
