### ISSUE TITLE
Failed to compile with MSVC 19.41.34120 amd64 Windows SDK 10.0.22621

### ISSUE THREAD

**Issue by scuzqy** [google/highway#2450]
Build environment:
compiler: MSVC 19.41.34120.
generator: Ninja. 
platform: Windows 10.0.19045 amd64.
Windows SDK 10.0.22621
`CMAKE_CXX_FLAGS="/arch:AVX2 /W4"`

Header from Windows sdk `<rpcndr.h>` introduced macro `small` as `char` alias
`#define small char`
compilation of math_test.cc fails when it reaches a template variable declaration [const T small](https://github.com/google/highway/blob/21a6bb018f5dc579818d88b209272cd765130ad9/hwy/contrib/math/math_test.cc#L459)
```
<path/to/math_test.cc> error C2638: 'T' followed by ‘char’ is illegal (did you forget a ';'?)

(and hundreds of error lines)
```

Chain of include

`"hwy/nanobenchmark.h"` <= `"hwy/timer.h"` <= `<windows.h> ` <= `....` <= `<rpcndr.h>`

Possible fixes:

1 In `hwy/timer.h"`
change 
`#include <windows.h>`
to
```
#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif WIN32_LEAN_AND_MEAN
#include <windows.h>
```
This globally apply `WIN32_LEAN_AND_MEAN` to every file referencing hwy timer

2  Define `WIN32_LEAN_AND_MEAN`, but in `math_test.cc`, or a file closer to the beginning of include chain

3 Simply rename the var
