### ISSUE TITLE
1.3.0 fails to build on FreeBSD

### ISSUE THREAD

**Issue by jbeich** [google/highway#2669]
Regressed by 195cff95d4fb. FreeBSD >= 12.2 (and DragonFly >= 6.0) support both [pthread_set_name_np(3)](https://man.freebsd.org/pthread_set_name_np/3) and [pthread_setname_np(3)](https://man.freebsd.org/pthread_setname_np/3) but only the latter returns a value. Note, FreeBSD < 12.2 [hasn't been supported](https://www.freebsd.org/security/#sup) since 2022-03-31.

```c++
In file included from hwy/examples/profiler_example.cc:19:
hwy/contrib/thread_pool/thread_pool.h:66:16: error: invalid operands to binary expression ('int' and 'void')
   66 |   HWY_ASSERT(0 == pthread_set_name_np(pthread_self(), buf));
      |              ~ ^  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
hwy/base.h:350:44: note: expanded from macro 'HWY_ASSERT'
  350 | #define HWY_ASSERT(condition) HWY_ASSERT_M(condition, "")
      |                                            ^~~~~~~~~
hwy/base.h:346:11: note: expanded from macro 'HWY_ASSERT_M'
  346 |     if (!(condition)) {                            \
      |           ^~~~~~~~~
```
